### ISSUE TITLE
View structures with pseudoknots

### ISSUE THREAD

**Issue by VonBoss** [r2dt-bio/R2DT#91]
Is there a way to export secondary figures with the pseudoknots visible? 
The MD file makes it sound like removing the pseudoknots is optional?

**Comment by davidhoksza** [comment]
Funny you ask because I started working on enabling this feature in Traveler (the program responsible for laying out the structures within the R2DT pipeline) today :) I started developing this feature about three years ago, but it never got into production. Should be ready in a week or so. Once ready, we can make it available via R2DT.

**Comment by VonBoss** [comment]
Brilliant! I would definitely appreciate that! Thank you.

**Comment by VonBoss** [comment]
I'm curious if you were able to implement your new feature.

**Comment by davidhoksza** [comment]
Just yesterday, I pushed it to [Traveler](https://github.com/cusbg/traveler/). See the corresponding section of README. However, it might take some time before it gets into R2DT. Currently, @AntonPetrov is testing it. But if you have a concrete template, you could try using Traveler directly. Or if you are interested in a single (or a few) structure only, I could run it for you...

**Comment by AntonPetrov** [comment]
@davidhoksza is right, I am working on integrating pseudoknot visualisation into R2DT right now. 

@VonBoss - if you are willing to send me your sequence(s) at _contact_ @ **antonpetrov** `.com`, I can test them and send you back the images (as long as the R2DT template for that RNA has pseudoknots of course).
